services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "2375:2375" # Docker daemon port
    env_file: .env
    privileged: true
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DOCKER_TLS_CERTDIR=""
    volumes:
      - dind-storage:/var/lib/docker

volumes:
  dind-storage:
